import { Inputs } from "./types";

export const DEFAULTS: Inputs = {
  students: 700,
  teachersFTE: 50,
  adoptionRate: 1,
  avgSalary: 48892,
  weeksPerYear: 39,
  weeklyHoursTotal: 54,
  weeklyMarkingHours: 10,
  weeklyAiAdminHours: 8,
  preset: "Expected",
  markingReductionCustom: 0.45,
  otherReductionCustom: 0.25,
  sickdayReductionCustom: 0.05,
  attritionReductionCustom: 0.02,
  sickDaysPerTeacher: 7,
  supplyDailyCost: 170,
  attritionRate: 0.088,
  replacementCost: 20000,
  aiBasePrice: 300,
  aiPricePerTeacher: 30,
  tier1StudentLimit: 100,
  tier2StudentLimit: 500,
  tier1PricePerStudent: 0,
  tier2PricePerStudent: 1,
  tier3PricePerStudent: 2,
  aiCostingMode: "SimplePricing",
  examParticipationRate: 0.8,
  assessmentsPerStudentPerYear: 6,
  baseInputTokensPerAssessment: 1500,
  baseOutputTokensPerAssessment: 900,
  tokenMultMaths: 1.4,
  tokenMultEnglish: 1.0,
  tokenMultScience: 1.2,
  tokenMultHumanities: 1.1,
  tokenMultOther: 1.0,
  gbpPer1MInputTokens: 0.0734,
  gbpPer1MOutputTokens: 0.2936,
  licenceFeeAnnual: 2000,
  subjectPreset: "Mixed",
  presetHumanitiesWeight: 0.65,
  presetStemWeight: 0.65,
  trainingOneTime: 2000,
  setupOneTime: 750,
};
